// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaO6nl3hPZYScriOpu1YIVQ5Zn7i6TjI4',
    appId: '1:693334397202:web:af038de0f6a501a727a3cb',
    messagingSenderId: '693334397202',
    projectId: 'flutter-todo-app-6c3c9',
    authDomain: 'flutter-todo-app-6c3c9.firebaseapp.com',
    storageBucket: 'flutter-todo-app-6c3c9.firebasestorage.app',
    measurementId: 'G-RE69YM55P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMybgVSrW147TLmAJfSih5N_8_Z0U8N0A',
    appId: '1:693334397202:android:3e96994bd194861727a3cb',
    messagingSenderId: '693334397202',
    projectId: 'flutter-todo-app-6c3c9',
    storageBucket: 'flutter-todo-app-6c3c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT1vdFfKkIb9VEq-g1HB0aNSRkfb_CVqw',
    appId: '1:693334397202:ios:d0cc69141c38b3a727a3cb',
    messagingSenderId: '693334397202',
    projectId: 'flutter-todo-app-6c3c9',
    storageBucket: 'flutter-todo-app-6c3c9.firebasestorage.app',
    iosBundleId: 'com.example.uptodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT1vdFfKkIb9VEq-g1HB0aNSRkfb_CVqw',
    appId: '1:693334397202:ios:d0cc69141c38b3a727a3cb',
    messagingSenderId: '693334397202',
    projectId: 'flutter-todo-app-6c3c9',
    storageBucket: 'flutter-todo-app-6c3c9.firebasestorage.app',
    iosBundleId: 'com.example.uptodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaO6nl3hPZYScriOpu1YIVQ5Zn7i6TjI4',
    appId: '1:693334397202:web:6b5ae34a6f0d6b0d27a3cb',
    messagingSenderId: '693334397202',
    projectId: 'flutter-todo-app-6c3c9',
    authDomain: 'flutter-todo-app-6c3c9.firebaseapp.com',
    storageBucket: 'flutter-todo-app-6c3c9.firebasestorage.app',
    measurementId: 'G-VERBZQE41M',
  );
}
